### ISSUE TITLE
[Crash] minecraft 1.19.2, Mod version 1.7   Index -1 out of bounds for length 129

### ISSUE THREAD

**Issue by DJAN90** [Traben-0/solid_mobs#21] opened 2023-08-31 04:06 UTC
[crash-2023-08-30_22.48.00-client.txt](https://github.com/Traben-0/solid_mobs/files/12482103/crash-2023-08-30_22.48.00-client.txt)

Forge - 43.2.14

**Comment by Traben-0** [comment] 2023-09-03 01:29
Duplicate of #20 I'm looking into it

**Closed by Traben-0** 2023-09-03 01:29 UTC
